
- name: Install nginx server
  yum:
    name: maven
    state: installed

- name: Create roboshop user account.
  ansible.builtin.user:
    name: roboshop

- name: Download and unzip the {{COMPONENT}} Zip
  include_role:
    name: common
    tasks_from: download.yml

- name: copy files from source to {{COMPONENT}} destination
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
    owner: roboshop
    group: roboshop
