
- name: Install nginx server
  yum:
    name: ["nodejs", "make", "gcc-c++"]
    state: installed


- name: Create roboshop user account.
  ansible.builtin.user:
    name: roboshop


- name: Download and unzip the {{COMPONENT}} Zip
  include_role:
    name: common
    tasks_from: download.yml


- name: copy files from source to {{COMPONENT}} destination
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install NPM from {{COMPONENT}} folder
  npm:
    path: /home/roboshop/{{COMPONENT}}
    state: latest
  become_user: roboshop

- name: Copy systemd.service file
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
    remote_src: no

- name: restart {{COMPONENT}} service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes
