
- name: Copy roboshop.conf file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo
    remote_src: no

- name: Install mongodb service
  yum:
    name: mongodb-org
    state: installed

- name: Replacing IP address in config file in /etc/mongod.conf
  replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start mongodb service
  systemd:
    name: mongod
    state: started

- name: Download and unzip the file
  unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp/
    remote_src: yes

- name: Run a js file containing MongoDB commands for catalogue.js
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/catalogue.js"
    idempotent: yes


- name: Run a js file containing MongoDB commands for users.js
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/users.js"
    idempotent: yes


