---
- hosts: all
  vars:
    URL: play.google.com
  tasks:
   - name: print play variables
     debug:
       msg: "{{URL}}"
     vars:
      URL: tasks.google.com
   - name: print play variables
     debug:
       msg: "{{URL}}"


- hosts: all
  tasks:
    - name: print play variables
      debug:
         msg: "{{URL}}"
#
#
- hosts: all
  vars_files:
    - var.yml
  vars:
    URL: yahoo.com
  tasks:
   - name: print var.tfvsrs variables
     debug:
       msg: "{{URL}}"


- hosts: all
  tasks:
    - name: register values
      shell: uptime
      register: out
    - name: pring the out value
      debug:
        msg: "{{out}}"



- hosts: all
  tasks:
  - name: facts
    set-fact:
      uptime: "{{out.start}}"

  - name: print out value from other play
    debug:
      msg: "{{uptime}}"